/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import company.Tools;

/**
 *
 * @author R-Walid Pro_Book
 */
public class fmain extends javax.swing.JFrame {

    /**
     * Creates new form fmain
     */
    public fmain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMybutton1 = new controls.JMybutton();
        jMybutton2 = new controls.JMybutton();
        jMybutton3 = new controls.JMybutton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMybutton4 = new controls.JMybutton();
        jMybutton6 = new controls.JMybutton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cmpany");
        setBackground(new java.awt.Color(153, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 0, 0));
        setMaximumSize(new java.awt.Dimension(953, 535));
        setMinimumSize(new java.awt.Dimension(953, 535));
        setPreferredSize(new java.awt.Dimension(953, 535));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jMybutton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMybutton1.setText("Gestion des personnel");
        jMybutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton1);
        jMybutton1.setBounds(110, 360, 170, 50);

        jMybutton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMybutton2.setText("gestion des vols");
        jMybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton2);
        jMybutton2.setBounds(700, 360, 170, 50);

        jMybutton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMybutton3.setText("Gestion desAvions");
        jMybutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton3);
        jMybutton3.setBounds(390, 160, 170, 50);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("La compagnie aérienne ");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 740, 63);

        jLabel5.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Contact us : rehamniawalid.info@gmail.com");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 480, 296, 13);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        jMybutton4.setText("Statistiques");
        jMybutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton4);
        jMybutton4.setBounds(590, 300, 111, 30);

        jMybutton6.setText("paramètres");
        jMybutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton6);
        jMybutton6.setBounds(260, 300, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/icon1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMybutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton3ActionPerformed
        Tools.open_form(new fconsultation());
        this.dispose();
    }//GEN-LAST:event_jMybutton3ActionPerformed

    private void jMybutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton1ActionPerformed
        // TODO add your handling code here:
        Tools.open_form(new formGestionPersonnel());
        this.dispose();
    }//GEN-LAST:event_jMybutton1ActionPerformed

    private void jMybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.open_form(new formgestionVol());
    }//GEN-LAST:event_jMybutton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        
    }//GEN-LAST:event_formWindowOpened

    private void jMybutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton6ActionPerformed
        // TODO add your handling code here:
        paramètres form = new paramètres();
        Tools.open_form(form);
        form.setDefaultCloseOperation(2);
    }//GEN-LAST:event_jMybutton6ActionPerformed

    private void jMybutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton4ActionPerformed
        // TODO add your handling code here:
        formStatistique forms = new formStatistique();
        Tools.open_form(forms);
        forms.setDefaultCloseOperation(2);
    }//GEN-LAST:event_jMybutton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private controls.JMybutton jMybutton1;
    private controls.JMybutton jMybutton2;
    private controls.JMybutton jMybutton3;
    private controls.JMybutton jMybutton4;
    private controls.JMybutton jMybutton6;
    // End of variables declaration//GEN-END:variables
}
