/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.rapport;
import static Forms.formConsulterRapport.glob;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author R-Walid Pro_Book
 */
public class formPrintRapport extends javax.swing.JFrame {

    /**
     * Creates new form formPrintRapport
     */
    public formPrintRapport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnprint = new controls.JMybutton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 550));
        setMinimumSize(new java.awt.Dimension(590, 550));
        setPreferredSize(new java.awt.Dimension(590, 550));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        table.setBackground(new java.awt.Color(255, 255, 102));
        table.setBorder(new javax.swing.border.MatteBorder(null));
        table.setForeground(new java.awt.Color(0, 0, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(95, 11, 393, 379);

        btnprint.setText(" Imprimer le rapport");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint);
        btnprint.setBounds(203, 449, 174, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/back7.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            table.print();
        } catch (PrinterException ex) {
            Logger.getLogger(formPrintRapport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling= code here:
        String date,heure,avion;
        rapport rap  = new rapport();
        date = rap.getDatRev(glob);
        heure = rap.getNbhrev(glob);
        avion=db.go.setAvionRev(glob);
        DefaultTableModel mod = (DefaultTableModel) table.getModel();
        mod.setRowCount(0);
        mod.addRow(new String[]{"Numéro de rapport","Numero d'avion"});
        mod.addRow(new Object[]{glob,avion});
        mod.addRow(new String[]{"",""});
        
        mod.addRow(new String[]{"Date du revision","Nombre d'heure de vol"});      
        mod.addRow(new String[]{date,heure});      
        mod.addRow(new String[]{"",""});
        
        mod.addRow(new Object[]{"Numero d'anomalier","Anomalier constatée"});
        db.go.fillToJTable("select NUMANO,ANO from anocon where NUMANO in(select anoano from r_menano where ANOTXT ="+glob+")",table,false);
          
        mod.addRow(new String[]{"",""});
        mod.addRow(new Object[]{"Numero du reparation","Reaparation effectuée"});
        db.go.fillToJTable("select numrep,rep from repeff where numrep in(select reprep from r_menrep where reptxt = "+glob+")",table,false);
        
        mod.addRow(new String[]{"",""});
        mod.addRow(new Object[]{"Numero d'organe ","Nom d'organe"});
        db.go.fillToJTable("select numorg,org from orgcha where numorg in(select orgorg from r_menorg where orgtxt = "+glob+")", table,false);
      //  formraport f = new formraport(); 
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrintRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrintRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrintRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrintRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrintRapport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybutton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
