/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.emp;
import Entity.r_equi;
import company.Tools;
import db.go;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author R-Walid Pro_Book
 */
public class formGestionPersonnel extends javax.swing.JFrame {

    /**
     * Creates new form formGestionPersonnel
     */
    public formGestionPersonnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtprenom = new controls.JTextBox(15);
        txtnom = new controls.JTextBox(15);
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtn = new controls.JTextBox(15);
        btnchercher = new controls.JMybutton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new controls.JTextBox(15);
        txtadr = new controls.JTextBox(15);
        txttel = new controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfonc = new controls.JTextBox(15);
        txtsal = new controls.JTextBox(15);
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMybutton7 = new controls.JMybutton();
        btnretrait = new controls.JMybutton();
        jMybutton2 = new controls.JMybutton();
        jMybutton3 = new controls.JMybutton();
        btnretrait1 = new controls.JMybutton();
        txtnvol = new javax.swing.JTextField();
        lblnvol = new javax.swing.JLabel();
        ok = new controls.JMybutton();
        txtresult = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMybutton1 = new controls.JMybutton();
        jMybutton4 = new controls.JMybutton();
        txtn1 = new controls.JTextBox(15);
        txtnemp = new javax.swing.JLabel();
        txtvoldate = new javax.swing.JTextField();
        lbldate = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1070, 640));
        setMinimumSize(new java.awt.Dimension(1070, 640));
        setPreferredSize(new java.awt.Dimension(1070, 640));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Numéro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 108, 55, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 136, 43, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Prénom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 161, 64, 23);

        txtprenom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtprenom.setForeground(new java.awt.Color(51, 255, 51));
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        getContentPane().add(txtprenom);
        txtprenom.setBounds(104, 161, 149, 23);

        txtnom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnom.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txtnom);
        txtnom.setBounds(104, 133, 149, 23);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table.setBackground(new java.awt.Color(255, 255, 204));
        table.setForeground(new java.awt.Color(51, 153, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nom", "Prénom", "Telephoe", "Adresse", "Date d'embouche", "Salaire", "Fonction"
            }
        ));
        table.setGridColor(new java.awt.Color(255, 0, 0));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(259, 75, 795, 295);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("les Personnel du parc d'aéronefs ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(247, 0, 582, 46);

        txtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtn.setForeground(new java.awt.Color(51, 255, 51));
        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        getContentPane().add(txtn);
        txtn.setBounds(104, 105, 149, 23);

        btnchercher.setText("Rechercher employée");
        btnchercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchercherActionPerformed(evt);
            }
        });
        getContentPane().add(btnchercher);
        btnchercher.setBounds(276, 388, 220, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Téléphone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 192, 83, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Adresse");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 70, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 245, 52, 23);

        txtdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtdate.setForeground(new java.awt.Color(51, 255, 51));
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate);
        txtdate.setBounds(104, 245, 149, 23);

        txtadr.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtadr.setForeground(new java.awt.Color(51, 255, 51));
        txtadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadrActionPerformed(evt);
            }
        });
        getContentPane().add(txtadr);
        txtadr.setBounds(104, 217, 149, 23);

        txttel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txttel.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txttel);
        txttel.setBounds(104, 189, 149, 23);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Salaire");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 276, 52, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Fonction");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 304, 62, 17);

        txtfonc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtfonc.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txtfonc);
        txtfonc.setBounds(104, 301, 149, 23);

        txtsal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtsal.setForeground(new java.awt.Color(51, 255, 51));
        txtsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalActionPerformed(evt);
            }
        });
        getContentPane().add(txtsal);
        txtsal.setBounds(104, 273, 149, 23);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Catégorie ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 75, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Navigant","Non navigant"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(104, 75, 149, 23);

        jMybutton7.setText("Ajouter nouvelle employée");
        jMybutton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton7);
        jMybutton7.setBounds(34, 342, 189, 28);

        btnretrait.setText("Ajouter au equipage du vol");
        btnretrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretraitActionPerformed(evt);
            }
        });
        getContentPane().add(btnretrait);
        btnretrait.setBounds(554, 431, 210, 32);

        jMybutton2.setText("nombre d'heure du vol par mois");
        jMybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton2);
        jMybutton2.setBounds(834, 431, 220, 33);

        jMybutton3.setText("Nombre total d'heure du vol");
        jMybutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton3);
        jMybutton3.setBounds(834, 391, 220, 33);

        btnretrait1.setText("Retrait employée naviguée");
        btnretrait1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretrait1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnretrait1);
        btnretrait1.setBounds(276, 426, 220, 32);

        txtnvol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnvol.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(txtnvol);
        txtnvol.setBounds(613, 495, 80, 23);

        lblnvol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblnvol.setText("N° vol");
        getContentPane().add(lblnvol);
        lblnvol.setBounds(564, 495, 42, 17);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(704, 505, 60, 30);

        txtresult.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtresult.setForeground(new java.awt.Color(255, 51, 51));
        txtresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultActionPerformed(evt);
            }
        });
        getContentPane().add(txtresult);
        txtresult.setBounds(888, 527, 90, 35);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("leur nombre d'heures de vol ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(834, 482, 214, 34);

        jMybutton1.setForeground(new java.awt.Color(255, 153, 51));
        jMybutton1.setText("Retour");
        jMybutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton1);
        jMybutton1.setBounds(460, 580, 98, 23);

        jMybutton4.setText("Consulter tout les employées");
        jMybutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton4);
        jMybutton4.setBounds(554, 391, 210, 32);

        txtn1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtn1.setForeground(new java.awt.Color(51, 255, 51));
        txtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtn1);
        txtn1.setBounds(386, 495, 110, 23);

        txtnemp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnemp.setText("N° d'employee");
        getContentPane().add(txtnemp);
        txtnemp.setBounds(276, 498, 100, 17);

        txtvoldate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtvoldate.setForeground(new java.awt.Color(51, 255, 0));
        txtvoldate.setText("aaaa/mm/jj");
        getContentPane().add(txtvoldate);
        txtvoldate.setBounds(613, 525, 80, 23);

        lbldate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbldate.setText("Date");
        getContentPane().add(lbldate);
        lbldate.setBounds(564, 525, 32, 17);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/back7.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1070, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void btnchercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchercherActionPerformed
        txtnemp.setVisible(true);
        txtn1.setVisible(true);
        if (txtn1.getText().equals("")) {
            Tools.msg("Saisis d'abord le N° d'employée");
        } else {
            try {
                db.go.fillToJTable("SELECT NUMEMP,NOMEMP,PREEMP,TELEMP,ADRESSE,DATEMB,SALEMP,FONCTION from emp where numemp = " + Integer.parseInt(txtn1.getText()), table, true);

            } catch (Exception ex) {
                Tools.msg("Erreur : " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnchercherActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void jMybutton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton7ActionPerformed
        // TODO add your handling code here:
        ///Je fait ce teste seulement pour detecter sur quelle table je vais travailler
        boolean navigant;
        String tab = (String) jComboBox1.getSelectedItem();
        if (tab.equals("Navigant")) {
            navigant = true;
        } else {
            navigant = false;
        }
        //   if (Tools.ContainEmptyField(this)) 
        if (txtn.getText().equals("") || txtnom.getText().equals("") || txtprenom.getText().equals("") || txttel.getText().equals("") || txtadr.getText().equals("")
                || txtdate.getText().equals("") || txtsal.getText().equals("") || txtfonc.getText().equals("")) {
            Tools.msg("Le remplissage des champs est obligatoire ");
        } else {
            try {
                int z;
                if (txtn.getText().equals("")) {
                    z = 0;
                } else {
                    z = Integer.parseInt(txtn.getText());

                }
                ///Vérifier la l'existence du N° dans DB
                if (db.go.checkExistenceOf("emp", "numemp", z)) {
                    Tools.msg("le numéro d'employée est déjas utiliser ");
                } else //i will save the employée
                {///Je les mettre ici pour eviter les erreur des champs fide  
                    String nom = txtnom.getText();
                    String prenom = txtprenom.getText();
                    String tel = txttel.getText();
                    String adr = txtadr.getText();
                    String date = txtdate.getText();
                    Double salaire = Double.parseDouble(txtsal.getText());
                    String fonc = txtfonc.getText();
                    emp e = new emp(z, nom, prenom, tel, adr, date, salaire, fonc, navigant);
                    e.add();
                    Tools.clearText(this);
                    String key = db.go.getAutoNumber("emp", "numemp");
                    txtn.setText(key);
                    txtdate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd")));
                }
            } catch (Exception ex) {
                Tools.msg("Erreur de saisir :" + ex.getMessage());
            }
        }//fin de else

    }//GEN-LAST:event_jMybutton7ActionPerformed

    private void txtsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalActionPerformed

    private void btnretraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretraitActionPerformed
        // TODO add your handling code here:
        try {
            if (txtn1.getText().equals("")) {
                txtnemp.setVisible(true);
                txtn1.setVisible(true);
                Tools.msg("Il faut saisir le N° d'employée");
            } else {
                lblnvol.setVisible(true);
                txtnvol.setVisible(true);
                ok.setVisible(true);
                lbldate.setVisible(true);
                txtvoldate.setVisible(true);
            }
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_btnretraitActionPerformed

    private void jMybutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtn1.getText().equals("")) {
                txtnemp.setVisible(true);
                txtn1.setVisible(true);
                Tools.msg("Il faut saisir le N° d'employée");
            } else {
                int numEmp = Integer.parseInt(txtn1.getText());
                jLabel10.setVisible(true);
                txtresult.setVisible(true);
                txtresult.setText(go.NBTHV(numEmp));
            }
        } catch (Exception ex) {
            txtresult.setText("0");
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_jMybutton3ActionPerformed


    private void btnretrait1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretrait1ActionPerformed
        // TODO add your handling code here:
        txtnemp.setVisible(true);
        txtn1.setVisible(true);
        if (txtn1.getText().equals("")) {
            Tools.msg("Il faut saisir le N° d'employée");
        } else {
            try {
                new emp(Integer.parseInt(txtn1.getText())).delete();
            } catch (Exception ex) {
                Tools.msg("Erreur :" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnretrait1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblnvol.setVisible(false);
        txtnvol.setVisible(false);
        ok.setVisible(false);
        txtresult.setVisible(false);
        jLabel10.setVisible(false);
        txtnemp.setVisible(false);
        txtn1.setVisible(false);
        lbldate.setVisible(false);
        txtvoldate.setVisible(false);
        txtn.setText(db.go.getAutoNumber("emp", "numemp"));
        txtdate.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd")));


    }//GEN-LAST:event_formWindowOpened

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        try {
            int nEmp = Integer.parseInt(txtn1.getText());
            String date = txtvoldate.getText();
            if (!db.go.checkExistenceOf("jvol", "jour", date)) {
                Tools.msg("Ce voyage n'a pas encore été programmé à cette date !");
            } else {
                r_equi eq = new r_equi(nEmp, Integer.parseInt(txtnvol.getText()), date);
                eq.add();
            }
        } catch (Exception ex) {
            Tools.msg("Erreur dans equipage :" + ex.getMessage());
        }

    }//GEN-LAST:event_okActionPerformed

    private void jMybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (txtn1.getText().equals("")) {
                txtnemp.setVisible(true);
                txtn1.setVisible(true);
                Tools.msg("Il faut saisir le N° d'employée");
            } else {
                int numEmp = Integer.parseInt(txtn1.getText());
                jLabel10.setVisible(true);
                txtresult.setVisible(true);
                txtresult.setText(go.NBMHV(numEmp));
            }
        } catch (Exception ex) {
            txtresult.setText("0");
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_jMybutton2ActionPerformed

    private void txtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultActionPerformed

    private void jMybutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton1ActionPerformed
        // TODO add your handling code here:t
        this.dispose();
        Tools.open_form(new fmain());
    }//GEN-LAST:event_jMybutton1ActionPerformed

    private void txtadrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadrActionPerformed

    private void jMybutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton4ActionPerformed
        try {
            db.go.fillToJTable("SELECT NUMEMP,NOMEMP,PREEMP,TELEMP,ADRESSE,DATEMB,SALEMP,FONCTION from emp order by nomemp ", table, true);

        } catch (Exception ex) {
            Tools.msg("Erreur : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMybutton4ActionPerformed

    private void txtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formGestionPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formGestionPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formGestionPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formGestionPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formGestionPersonnel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybutton btnchercher;
    private controls.JMybutton btnretrait;
    private controls.JMybutton btnretrait1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private controls.JMybutton jMybutton1;
    private controls.JMybutton jMybutton2;
    private controls.JMybutton jMybutton3;
    private controls.JMybutton jMybutton4;
    private controls.JMybutton jMybutton7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblnvol;
    private controls.JMybutton ok;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtadr;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtfonc;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtn1;
    private javax.swing.JLabel txtnemp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnvol;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtresult;
    private javax.swing.JTextField txtsal;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtvoldate;
    // End of variables declaration//GEN-END:variables
}
