/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import company.Tools;
import db.go;

/**
 *
 * @author R-Walid Pro_Book
 */
public class formConsulterRapport extends javax.swing.JFrame {

    /**
     * Creates new form formConsulterRapport
     */
    public formConsulterRapport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtna = new controls.JTextBox(15);
        jLabel9 = new javax.swing.JLabel();
        txtnr = new controls.JTextBox(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMybutton1 = new controls.JMybutton();
        jMybutton2 = new controls.JMybutton();
        btnprint = new controls.JMybutton();
        jMybutton9 = new controls.JMybutton();
        btnprint1 = new controls.JMybutton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 610));
        setMinimumSize(new java.awt.Dimension(700, 610));
        setPreferredSize(new java.awt.Dimension(700, 610));
        getContentPane().setLayout(null);

        txtna.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtna.setForeground(new java.awt.Color(51, 255, 51));
        txtna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnaActionPerformed(evt);
            }
        });
        getContentPane().add(txtna);
        txtna.setBounds(572, 348, 49, 23);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("N° du rapport");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(432, 430, 94, 17);

        txtnr.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnr.setForeground(new java.awt.Color(51, 255, 51));
        txtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnrActionPerformed(evt);
            }
        });
        getContentPane().add(txtnr);
        txtnr.setBounds(536, 427, 85, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° rapport", "Avion concernée", "N°  d'ecreteure", "Date de revision", "Nombre d'heure d'avion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 85, 679, 253);

        jMybutton1.setText("Afficher Tout les rapports");
        jMybutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton1);
        jMybutton1.setBounds(74, 349, 183, 23);

        jMybutton2.setText("Afficher Les rapports d'avion N°");
        jMybutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton2);
        jMybutton2.setBounds(332, 349, 230, 23);

        btnprint.setText("Imprimer le rapport");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint);
        btnprint.setBounds(426, 461, 195, 66);

        jMybutton9.setBackground(new java.awt.Color(255, 255, 0));
        jMybutton9.setForeground(new java.awt.Color(255, 153, 51));
        jMybutton9.setText("Retour");
        jMybutton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton9);
        jMybutton9.setBounds(300, 548, 94, 23);

        btnprint1.setText("Creer nouvelle rapport");
        btnprint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprint1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint1);
        btnprint1.setBounds(62, 461, 195, 66);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Gestion dU rapport texte ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(118, 12, 458, 55);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/back7.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnaActionPerformed

    private void txtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnrActionPerformed
    static int glob;
    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed

        try {
            int numtxt = Integer.parseInt(txtnr.getText());
            if (db.go.checkExistenceOf("raptxt", "numtxt", numtxt)) {
                glob=numtxt;
                formPrintRapport frm = new formPrintRapport();
                Tools.open_form(frm);
                frm.setDefaultCloseOperation(2);
            }
            else
                Tools.msg("Il n'y a pas de rapport avec ce numéro ");
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());

        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void jMybutton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.open_form(new fmain());
    }//GEN-LAST:event_jMybutton9ActionPerformed

    private void btnprint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprint1ActionPerformed
        // TODO add your handling code here:
        formraport form = new formraport();
        Tools.open_form(form);
        form.setDefaultCloseOperation(2);
    }//GEN-LAST:event_btnprint1ActionPerformed

    private void jMybutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton1ActionPerformed
        // TODO add your handling code here:
                try{
         go.fillToJTable("select numtxt,avionrev,ecreteur,datrev,nbhrev from raptxt", jTable1,true);   
        }
        catch(Exception ex){
            Tools.msg(ex.getMessage());
            
        }
        
    }//GEN-LAST:event_jMybutton1ActionPerformed

    private void jMybutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton2ActionPerformed
        // TODO add your handling code here:txtna
        try{
            int key=Integer.parseInt(txtna.getText());
        go.fillToJTable("select numtxt,avionrev,ecreteur,datrev,nbhrev from raptxt where numtxt = "+key, jTable1,true);    
        }
        catch(Exception ex){
            Tools.msg(ex.getMessage());
            
        }
        
    }//GEN-LAST:event_jMybutton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formConsulterRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formConsulterRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formConsulterRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formConsulterRapport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formConsulterRapport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybutton btnprint;
    private controls.JMybutton btnprint1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private controls.JMybutton jMybutton1;
    private controls.JMybutton jMybutton2;
    private controls.JMybutton jMybutton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtna;
    private javax.swing.JTextField txtnr;
    // End of variables declaration//GEN-END:variables
}
