/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.escale;
import Entity.r_fournit;
import company.Tools;

/**
 *
 * @author R-Walid Pro_Book
 */
public class formEscale extends javax.swing.JFrame {

    /**
     * Creates new form formEscale
     */
    public formEscale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtne = new controls.JTextBox(15);
        txtd = new controls.JTextBox(15);
        txth = new controls.JTextBox(15);
        jLabel7 = new javax.swing.JLabel();
        ok = new controls.JMybutton();
        jMybutton1 = new controls.JMybutton();
        jLabel6 = new javax.swing.JLabel();
        txtnvol = new controls.JTextBox(15);
        txtvile = new controls.JTextBox(15);
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 515));
        setMinimumSize(new java.awt.Dimension(500, 515));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("veuillez fournir la liste d'escale d'un vol");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 0, 447, 42);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° escale", "Vile Escale"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(79, 71, 335, 186);

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel2.setText("Voici la liste d'escales possible");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 46, 324, 24);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Durée d'escale");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(96, 407, 105, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("N° d'escale");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(96, 347, 99, 17);

        txtne.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtne.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txtne);
        txtne.setBounds(336, 347, 63, 23);

        txtd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtd.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txtd);
        txtd.setBounds(336, 407, 63, 23);

        txth.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txth.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txth);
        txth.setBounds(336, 377, 63, 23);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("temps considéré pour l'atteindre");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(96, 377, 230, 17);

        ok.setText("ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(191, 450, 87, 32);

        jMybutton1.setText("Ajouter éscale");
        jMybutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton1);
        jMybutton1.setBounds(115, 268, 120, 23);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("N° du vol");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(96, 317, 139, 17);

        txtnvol.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnvol.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txtnvol);
        txtnvol.setBounds(336, 317, 63, 23);

        txtvile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtvile.setForeground(new java.awt.Color(51, 255, 51));
        txtvile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvileActionPerformed(evt);
            }
        });
        getContentPane().add(txtvile);
        txtvile.setBounds(253, 267, 123, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/back7.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:

        if (txtne.getText().equals("") || txth.getText().equals("") || txtd.getText().equals("")) {
            Tools.msg("Il faut remplir tout les champs");
        } else {
            try {
                int num = Integer.parseInt(txtne.getText());
                int numV = Integer.parseInt(txtnvol.getText());
                if (!db.go.checkExistenceOf("escale", "numesc", num)) {
                    Tools.msg("Cette N° d'escale n'existe pas");
                } else if (new escale().checkAffectingEscale(numV, num)) {
                    Tools.msg("Cete N° d'escale est déja fournit au cette vol");
                } else {
                    r_fournit fournit = new r_fournit(numV, num, txth.getText(), txtd.getText());
                    fournit.add();
                    Tools.clearText(this);
                    txtne.requestFocus();
                }
            } catch (Exception ex) {
                Tools.msg(ex.getMessage());
            }
        }
    }//GEN-LAST:event_okActionPerformed

    private void jMybutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton1ActionPerformed
        // TODO add your handling code here:
        if (txtvile.getText().equals("")) {
            Tools.msg("Remplissez le champ ville");
        } else {
            try {
                escale es = new escale(txtvile.getText());
                es.add();
                Tools.clearText(this);
                txtvile.requestFocus();
                db.go.fillToJTable("select * from escale", jTable1, true);
            } catch (Exception ex) {
                Tools.msg(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jMybutton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        db.go.fillToJTable("select * from escale", jTable1, true);
    }//GEN-LAST:event_formWindowOpened

    private void txtvileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvileActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtvileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEscale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEscale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private controls.JMybutton jMybutton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private controls.JMybutton ok;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextField txth;
    private javax.swing.JTextField txtne;
    private javax.swing.JTextField txtnvol;
    private javax.swing.JTextField txtvile;
    // End of variables declaration//GEN-END:variables
}
