/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.mentionnerAno;
import Entity.mentionnerOrg;
import Entity.mentionnerRep;
import Entity.organeChangee;
import Entity.rapport;
import Entity.reparation;
import static Forms.formConsulterRapport.glob;
import company.Tools;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author R-Walid Pro_Book
 */
public class formraport extends javax.swing.JFrame {

    /**
     * Creates new form formraport
     */
    public formraport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        rapport = new javax.swing.JTextArea();
        choix = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtna = new controls.JTextBox(15);
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnr = new controls.JTextBox(15);
        Valider = new controls.JMybutton();
        btnajouter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtne = new controls.JTextBox(15);
        lblne = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(460, 490));
        setMinimumSize(new java.awt.Dimension(460, 490));
        setPreferredSize(new java.awt.Dimension(460, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        rapport.setBackground(new java.awt.Color(255, 255, 153));
        rapport.setColumns(20);
        rapport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rapport.setRows(5);
        rapport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(rapport);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(53, 256, 342, 147);

        choix.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anomalie constatée", "Réparation effectuée","Organe changé" }));
        getContentPane().add(choix);
        choix.setBounds(154, 204, 241, 43);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 139, 119));
        jLabel1.setText("Citer :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(53, 204, 97, 42);

        txtna.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtna.setForeground(new java.awt.Color(51, 255, 51));
        txtna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnaActionPerformed(evt);
            }
        });
        getContentPane().add(txtna);
        txtna.setBounds(195, 102, 148, 23);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("N° avion");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(118, 105, 73, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("N° rapport");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(119, 76, 72, 17);

        txtnr.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnr.setForeground(new java.awt.Color(51, 255, 51));
        txtnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnrActionPerformed(evt);
            }
        });
        getContentPane().add(txtnr);
        txtnr.setBounds(195, 73, 148, 23);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(205, 161, 65, 23);

        btnajouter.setBackground(new java.awt.Color(0, 255, 0));
        btnajouter.setFont(new java.awt.Font("Vani", 3, 10)); // NOI18N
        btnajouter.setText("Ajouter ");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouter);
        btnajouter.setBounds(188, 413, 100, 27);

        jLabel2.setFont(new java.awt.Font("Aparajita", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Création du rapport texte");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 8, 381, 47);

        txtne.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtne.setForeground(new java.awt.Color(51, 255, 51));
        txtne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtneActionPerformed(evt);
            }
        });
        getContentPane().add(txtne);
        txtne.setBounds(195, 131, 148, 23);

        lblne.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblne.setText("N° écriteur");
        getContentPane().add(lblne);
        lblne.setBounds(115, 134, 76, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/back7.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 460, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int numRapport;
    private void txtnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnaActionPerformed

    private void txtnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnrActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnrActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            
        }
        catch(Exception ex){
            Tools.msg(""+ex);
        }
        txtnr.setText(db.go.getAutoNumber("raptxt", "numtxt"));
       txtnr.setEnabled(false);
        rapport.setVisible(false);
        btnajouter.setVisible(false);
        choix.setVisible(false);
        jLabel1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        String nr = txtnr.getText();
        String na = txtna.getText();
        String ne = txtne.getText();
        if (nr.equals("") || na.equals("") || ne.equals("")) {
            Tools.msg("Il faut remplir tout les champ");
        } else {//Creation du rapport
            try {
                glob = Integer.parseInt(txtnr.getText());
                rapport rap = new rapport(glob, Integer.parseInt(na), Integer.parseInt(ne));
                if (rap.add()) {
                    rapport.setVisible(true);
                    choix.setVisible(true);
                    jLabel1.setVisible(true);
                    txtnr.setVisible(false);
                    txtna.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel12.setVisible(false);
                    btnajouter.setVisible(true);
                    Valider.setVisible(false);
                    txtne.setVisible(false);
                    lblne.setVisible(false);
                    ///update avion information : Reset nbhddrev, ...
                    Double numAv = Double.parseDouble(txtna.getText());
                    try {
                        db.go.runNonQuery("update avion set NBHDDREV = 0 where numav = " + numAv);
                        db.go.runNonQuery("update avion set situation = 'pret' where numav = " + numAv);
                    } catch (SQLException ex) {
                        Logger.getLogger(formraport.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (Exception ex) {
                Tools.msg(ex.getMessage());
            }
        }

    }//GEN-LAST:event_ValiderActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        // TODO add your handling code here:
        try {
            String select = (String) choix.getSelectedItem();
            String info = rapport.getText();
            int k;
            numRapport = Integer.parseInt(txtnr.getText());
            switch (select) {
                case "Anomalie constatée": {
                    k = db.go.saveData("anocon", "numano", "ano", info);
                    mentionnerAno a = new mentionnerAno(numRapport, k);
                    a.add();
                }
                break;
                case "Réparation effectuée": {
                    k = db.go.saveData("repeff", "numrep", "rep", info);
                    mentionnerRep rep = new mentionnerRep(numRapport, k);
                    rep.add();
                }
                break;
                case "Organe changé": {
                    organeChangee orgcha = new organeChangee(1, info);
                    k = db.go.saveData("orgcha", "numorg", "org", info);
                    mentionnerOrg menorg = new mentionnerOrg(numRapport, k);
                    menorg.add();
                }
                break;
            }
            rapport.setText("");
            rapport.requestFocus();
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }
    }//GEN-LAST:event_btnajouterActionPerformed

    private void txtneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formraport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formraport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formraport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formraport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formraport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMybutton Valider;
    private javax.swing.JButton btnajouter;
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblne;
    private javax.swing.JTextArea rapport;
    private javax.swing.JTextField txtna;
    private javax.swing.JTextField txtne;
    private javax.swing.JTextField txtnr;
    // End of variables declaration//GEN-END:variables
}
