/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import company.Tools;

/**
 *
 * @author R-Walid Pro_Book
 */
public class paramètres extends javax.swing.JFrame {

    /**
     * Creates new form paramètres
     */
    public paramètres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temp = new javax.swing.JComboBox<>();
        jMybutton1 = new controls.JMybutton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(359, 210));
        setMinimumSize(new java.awt.Dimension(359, 210));
        setPreferredSize(new java.awt.Dimension(359, 210));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel32.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 255));
        jLabel32.setText("paramètres");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(73, 0, 229, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("L'intervalle entre les mises à jour de La base");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 72, 324, 17);

        temp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"0s", "01min", "10min","30min","1h","2h" }));
        temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempActionPerformed(evt);
            }
        });
        getContentPane().add(temp);
        temp.setBounds(139, 107, 83, 27);

        jMybutton1.setText("Ok");
        jMybutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMybutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jMybutton1);
        jMybutton1.setBounds(139, 145, 83, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/back7.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tempActionPerformed

    private void jMybutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMybutton1ActionPerformed
        try {
            // company.Company.updateTime = (double) temp.getSelectedItem();
            String selected = (String) temp.getSelectedItem();
            long val = 0;
            switch (selected) {
                case "0s":
                    db.go.runNonQuery("delete from up");
                    db.go.runNonQuery("insert into up values(0,0)");
                    break;
                case "01min":
                    db.go.runNonQuery("delete from up");
                    db.go.runNonQuery("insert into up values(1,60000)");
                    break;
                case "10min":
                    db.go.runNonQuery("delete from up");
                    db.go.runNonQuery("insert into up values(2,600000)");
                    break;
                case "30min":
                    db.go.runNonQuery("delete from up");
                    db.go.runNonQuery("insert into up values(3,1800000)");
                    break;
                case "1h":
                    db.go.runNonQuery("delete from up");
                    db.go.runNonQuery("insert into up values(4,3600000)");
                    break;
                case "2h":
                    db.go.runNonQuery("delete from up");
                    db.go.runNonQuery("insert into up values(5,7200000)");
                    break;
            }
            this.dispose();
        } catch (Exception ex) {
            Tools.msg(ex.getMessage());
        }

    }//GEN-LAST:event_jMybutton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int s= db.go.getSelected();
        temp.setSelectedIndex(s);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paramètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paramètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paramètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paramètres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paramètres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private controls.JMybutton jMybutton1;
    private javax.swing.JComboBox<String> temp;
    // End of variables declaration//GEN-END:variables
}
